# shellcheck shell=sh

#
# System-wide POSIX profile
# Generated by /Users/j5pu/env/bin/rc

unset ENV

: "${ENV_TRACE=0}"; [ "${ENV_TRACE}" -eq 0 ] || set -x

if ! command -v reenv >/dev/null; then
  . "/Users/j5pu/env/etc/functions.d/rc.sh"

  env_source_dir "/Users/j5pu/env/etc/functions.d/00-common"
  env_source_dir "/Users/j5pu/env/etc/functions.d/Darwin"
  env_source_dir "/Users/j5pu/env/etc/functions.d/pro"
fi

if ! echo "${PATH}" | grep -q "/Users/j5pu/env/bin:"; then
  export PATH="/Users/j5pu/env/bin:${PATH}"
  : "${HOSTNAME=$(hostname)}"; export HOSTNAME

  export ENV_CUSTOM="/Users/j5pu/env/custom"
  export ENV_CUSTOM_PROFILE_D="/Users/j5pu/env/custom/profile.d"
  export ENV_CUSTOM_RC_D="/Users/j5pu/env/custom/rc.d"
  export ENV_ETC="/Users/j5pu/env/etc"
  export ENV_ETC_COMPLETION="/Users/j5pu/env/etc/bash_completion.d"
  export ENV_ETC_FUNCTIONS="/Users/j5pu/env/etc/functions.d"
  export ENV_ETC_PROFILE_D="/Users/j5pu/env/etc/profile.d"
  export ENV_ETC_RC_D="/Users/j5pu/env/etc/rc.d"
  export ENV_GENERATED="/Users/j5pu/env/generated"
  export ENV_GENERATED_PROFILE_D="/Users/j5pu/env/generated/profile.d"
  export ENV_GENERATED_RC_D="/Users/j5pu/env/generated/rc.d"
  export ENV_SUPPORTED="00-common arch Darwin debian fedora Linux rhel rhel_fedora pro"
  export ENV_TOP="/Users/j5pu/env"
  export ID_LIKE=""
  export MACOS="true"
  export SUDO="/usr/bin/sudo"
  export UNAME="Darwin"
  export VGA="1"

  env_source_dir "/Users/j5pu/env/etc/profile.d/constants.d/00-common"
  env_source_dir "/Users/j5pu/env/etc/profile.d/constants.d/Darwin"
  env_source_dir "/Users/j5pu/env/etc/profile.d/constants.d/pro"
  env_source_dir "/Users/j5pu/env/etc/profile.d/vars.d/00-common"
  env_source_dir "/Users/j5pu/env/etc/profile.d/vars.d/Darwin"
  env_source_dir "/Users/j5pu/env/etc/profile.d/vars.d/pro"

  env_source_dir "/Users/j5pu/env/etc/profile.d/hooks.d/00-common/bash"
  env_source_dir "/Users/j5pu/env/etc/profile.d/hooks.d/00-common/sh"
  env_source_dir "/Users/j5pu/env/etc/profile.d/hooks.d/Darwin/bash"
  env_source_dir "/Users/j5pu/env/etc/profile.d/hooks.d/Darwin/sh"
  env_source_dir "/Users/j5pu/env/etc/profile.d/hooks.d/pro/bash"
  env_source_dir "/Users/j5pu/env/etc/profile.d/hooks.d/pro/sh"

  . "/Users/j5pu/env/generated/profile.d/00-common.sh"
  . "/Users/j5pu/env/generated/profile.d/Darwin.sh"
  . "/Users/j5pu/env/generated/profile.d/pro.sh"

env_source_dir "/Users/j5pu/env/custom/profile.d"
fi

#
# RC for interactive shells has been sourced already
: "${ENV_SOURCED=0}"

if { [ "${PS1-}" ] || echo "$-" | grep -q i; } && [ "${ENV_SOURCED}" -eq 0 ]; then
  ENV_SOURCED=1

  unalias cp egrep fgrep grep l l. la ll lld ls mv rm xzegrep xzfgrep xzgrep zegrep zfgrep zgrep 2>/dev/null

  env_source_dir "/Users/j5pu/env/etc/rc.d/aliases.d/00-common"
  env_source_dir "/Users/j5pu/env/etc/rc.d/aliases.d/Darwin"
  env_source_dir "/Users/j5pu/env/etc/rc.d/aliases.d/pro"

  env_source_dir "/Users/j5pu/env/etc/rc.d/hooks.d/00-common/bash"
  env_source_dir "/Users/j5pu/env/etc/rc.d/hooks.d/00-common/sh"
  env_source_dir "/Users/j5pu/env/etc/rc.d/hooks.d/Darwin/bash"
  env_source_dir "/Users/j5pu/env/etc/rc.d/hooks.d/Darwin/sh"
  env_source_dir "/Users/j5pu/env/etc/rc.d/hooks.d/pro/bash"
  env_source_dir "/Users/j5pu/env/etc/rc.d/hooks.d/pro/sh"

  . "/Users/j5pu/env/generated/rc.d/00-common/dirs.sh"
  . "/Users/j5pu/env/generated/rc.d/Darwin/dirs.sh"
  . "/Users/j5pu/env/generated/rc.d/pro/dirs.sh"

  if [ "${SUDO-}" ]; then
    . "/Users/j5pu/env/generated/rc.d/00-common/sudo.sh"
    . "/Users/j5pu/env/generated/rc.d/Darwin/sudo.sh"
    . "/Users/j5pu/env/generated/rc.d/pro/sudo.sh"
  fi

  if has complete; then
    . "/Users/j5pu/env/etc/bash_completion.d/rc.bash"

    env_source_dir "/Users/j5pu/env/etc/bash_completion.d/00-common"
    env_source_dir "/Users/j5pu/env/etc/bash_completion.d/Darwin"
    env_source_dir "/Users/j5pu/env/etc/bash_completion.d/pro"
  fi

env_source_dir "/Users/j5pu/env/custom/rc.d"
fi

export ENV="/Users/j5pu/env/.env.sh"

[ "${ENV_TRACE}" -eq 0 ] || set +x
