#!/bin/sh

cd "$(command -p dirname "$0")" || exit
cd "$(command -p git rev-parse --show-toplevel)" || exit
export ENV="${PWD}/.profile.dev"
export RC="${PWD}"
"${RC}/bin/bash" -c "open /Applications/PyCharm.app"
