#!/bin/sh

echo 2

set -eu

RC="$(cd "$(command -p dirname "$0")/.."; pwd -P)"; export RC
echo "$@"
#echo exec "$(PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" command -v bash)" \
#  --init-file "${RC}/dev/.profile" --rcfile "${RC}/dev/.bashrc" "$@" -c "echo $PATH >/tmp/path"
