#!/bin/sh

set -eu

compare() {
  tee "${tmp}" >/dev/null
  [ "$(cat "${tmp}")" = "$(cat "$1")" ] || { sudo mv "${tmp}" "$1"; sudo systemctl daemon-reload; return 1; }
}

if ! dpkg -s x11vnc | grep -q "Status: install ok installed"; then
  sudo apt-get -qq update
  sudo apt-get -qq install -y x11vnc
fi

tmp="$(mktemp)"

sudo mkdir -p /etc/systemd/system
compare /etc/systemd/system/x11vnc.service <<EOF
[Unit]
Description=X11 VNC Remote Desktop Service
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/bin/x11vnc -avahi -ncache 10 -norc -forever -shared -bg -rfbauth /etc/password -allow 192.168.1. -nopw -autoport 5900 -o /var/log/x11vnc.log

[Install]
WantedBy=multi-user.target
EOF

compare /etc/systemd/system/x11vnc.service <<EOF || { sudo systemctl enable graphical.target; >&2 echo "reboot"; }
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Graphical Interface
Documentation=man:systemd.special(7)
Requires=multi-user.target
After=multi-user.target
Conflicts=rescue.target
Wants=display-manager.service
Wants=x11vnc.service
AllowIsolate=yes

[Install]
Alias=default.target
EOF
